version: '3'

services:

  hms-db:
    image: "mysql:8.0.18"
    ports:
      - "3306:53306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  hms-thrift:
    build:
      context: hms-thrift
      dockerfile: Dockerfile
    image: hms-thrift:3.1.0
    ports:
      - "9083:9083"
    depends_on:
      - hms-db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  presto-coordinator:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        - presto_version=${PRESTO_VERSION}
    image: presto-server:${PRESTO_VERSION}
    ports:
      - "8080:8080"
    environment:
      IS_COORDINATOR: "true"
      COORDINATOR_IS_WORKER: ${COORDINATOR_IS_WORKER}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ICEBERG_DIR: ${ICEBERG_DIR}
