version: '3'

services:

  worker:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        - presto_version=$PRESTO_VERSION
    image: presto-server:${PRESTO_VERSION}
    environment:
      IS_COORDINATOR: "false"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ICEBERG_DIR: ${ICEBERG_DIR}
