version: '3'

services:

  presto-worker:
    build:
      context: server
      dockerfile: Dockerfile
      args:
        - PRESTO_VERSION=${PRESTO_VERSION}
    image: presto-server:${PRESTO_VERSION}
    environment:
      - IS_COORDINATOR=false
      - HIVE_SECURITY=${HIVE_SECURITY:-legacy}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GCS_ACCOUNT_EMAIL=${GCS_ACCOUNT_EMAIL}
      - GCS_PRIVATE_KEY_ID=${GCS_PRIVATE_KEY_ID}
      - GCS_PRIVATE_KEY=${GCS_PRIVATE_KEY}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_CLIENT_ID=${GCS_CLIENT_ID}
      - ICEBERG_DIR=${ICEBERG_DIR}
