apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-coordinator
  name: trino-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      containers:
      - image: gettlabs/trino-server:351
        name: trino-coordinator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: IS_COORDINATOR
          value: "true"
        - name: COORDINATOR_IS_WORKER
          value: "true"
        envFrom:
        - configMapRef:
            name: trino-config
        - secretRef:
            name: trino-secrets
      restartPolicy: Always
      imagePullSecrets:
        - name: gettlabsdocker-v2
