apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator
  labels:
    app: presto-coordinator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31972
  selector:
    app: presto-coordinator
  type: NodePort
