apiVersion: v1
kind: Service
metadata:
  name: trino-coordinator
  labels:
    app: trino-coordinator
#  annotations:
#    kubernetes.io/service-name: '{{ .Release.Name }}'
#    external-dns.alpha.kubernetes.io/hostname: {{ .Values.Dns }}.
#    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
#    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: 'KubernetesCluster=algo-{{ .Release.Namespace }},environment=algo, release={{ .Release.Name }}'
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31972
  selector:
    app: trino-coordinator
  type: NodePort
#  type: LoadBalancer
