apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino-worker
  name: trino-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
      - image: gettlabs/trino-server:351
        name: trino-worker
        ports:
        - containerPort: 8080
        env:
        - name: IS_COORDINATOR
          value: "false"
        envFrom:
        - configMapRef:
            name: trino-config
        - secretRef:
            name: trino-secrets
      restartPolicy: Always
