apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-db
  template:
    metadata:
      labels:
        app: hms-db
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: mysql:8.0.18
        name: hms-db
        ports:
        - containerPort: 53306
      restartPolicy: Always
